steps:
# Step 1
#- name: 'gcr.io/cloud-builders/docker'
  #entrypoint: 'bash'
  #args: [
    #'-c', 
   # 'docker pull gcr.io/famous-palisade-356103/device-mngr:latest || exit 0'
  #]
# Step 2
- name: gcr.io/cloud-builders/docker
  args: [
    'build', 
    '-t', 
    'asia-east1-docker.pkg.dev/control-plane-358307/device-management/device-mgr:$REVISION_ID',
   # '-t',
    #'gcr.io/famous-palisade-356103/device-mngr:latest',
    '.'
  ]
#dir: 'my-app-vue'
# Step 2.2
- name: gcr.io/cloud-builders/docker
  args: [
    'push', 
    'asia-east1-docker.pkg.dev/control-plane-358307/device-management/device-mgr:$REVISION_ID'
  ]
# Step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  #args: ['apply', '-f', '*.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=device'
# Step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set', 
    'image', 
    'deployment', 
    'device-manager', 
    'devicemngr=asia-east1-docker.pkg.dev/control-plane-358307/device-management/device-mgr:$REVISION_ID'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=device'
# Push the image to Google Container Registry with the latest tag
images: [
    'asia-east1-docker.pkg.dev/control-plane-358307/device-management/device-mgr:$REVISION_ID'
  ]